spring:
  application:
    name: one
  datasource:
    url: jdbc:oracle:thin:@192.168.51.34:1521:XE
    username: C##KH_ISO
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
web:
  resource:
    static-locations: file:uploads/
mvc:
  static-path-pattern: /uploads/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 80
mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iso.plogues.question.model.dto, com.iso.plogues.question.comment.model.dto;
  
jwt:
  secret: p7Vq3mZ8kL1Xo9R2bT6nW4cF0HsJ8vQeA5uD3mZx7LpN2kV9sR1cG6hT0bY8fJ